---
    - name: install yum packages
      yum: name={{ item }} state=latest
      with_items:
      - httpd
      - mysql-server
      - php
      - php-mysql
      - php-mbstring
      - python-setuptools
    - name: install easy_install package
      easy_install: name=pip
    - name: install pip package
      pip: name=httplib2
    - name: copy index.html
      copy: src=tasks/index.html dest=/var/www/html
    - name: copy info.php
      copy: src=tasks/info.php dest=/var/www/html
    - name: start httpd
      service: name=httpd enabled=yes state=started
    - name: start mysqld
      service: name=mysqld enabled=yes state=started
    - name: check httpd is working
      uri: url=http://192.168.33.10/
